import os

from dotenv import load_dotenv
from google import genai


# ---------------------------------------------------------
# LOAD ENVIRONMENT VARIABLES
# ---------------------------------------------------------

load_dotenv()


# ---------------------------------------------------------
# LLM SETTINGS
# ---------------------------------------------------------

MODEL_NAME = "gemini-3.8-flash"


# ---------------------------------------------------------
# CREATE GEMINI CLIENT
# ---------------------------------------------------------

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError(
        "GEMINI_API_KEY not found. "
        "Please check your .env file."
    )

client = genai.Client(
    api_key=api_key
)


# ---------------------------------------------------------
# GENERATE GROUNDED ANSWER
# ---------------------------------------------------------

def generate_answer(
    question: str,
    evidence: list[dict]
) -> str:
    """
    Generate an answer using only the retrieved evidence.

    Parameters
    ----------
    question : str
        User's research question.

    evidence : list[dict]
        Retrieved and reranked evidence.

    Returns
    -------
    str
        Grounded answer generated by Gemini.
    """

    # -----------------------------------------------------
    # BUILD EVIDENCE TEXT
    # -----------------------------------------------------

    evidence_text = ""

    for index, item in enumerate(
        evidence,
        start=1
    ):

        evidence_text += (
            f"\nEvidence {index}\n"
            f"Source: {item['source']}\n"
            f"Page: {item['page']}\n"
            f"Text: {item['text']}\n"
        )


    # -----------------------------------------------------
    # SYSTEM INSTRUCTION
    # -----------------------------------------------------

    system_prompt = """
You are a healthcare research assistant.

Answer the user's question using ONLY the provided evidence.

Rules:

1. Do not add information that is not supported by the evidence.

2. If the evidence is insufficient to answer the question,
   clearly say that the available evidence is insufficient.

3. Do not diagnose diseases.

4. Do not recommend treatments.

5. Every important factual statement must be supported
   by the provided evidence.

6. Cite the relevant source and page immediately after
   the statement using this exact format:

   [Source: DIA_ChXX, Page: N]

7. At the end of the answer, include a section called:

   Sources:

8. Under Sources, list only the sources and pages that
   were actually used in the answer.

9. Do not invent source names, page numbers, or evidence.

10. Keep the answer concise and research-oriented.
"""


    # -----------------------------------------------------
    # USER PROMPT
    # -----------------------------------------------------

    user_prompt = f"""
Question:
{question}

Retrieved Evidence:
{evidence_text}

Using ONLY the retrieved evidence, provide a concise,
accurate, evidence-grounded answer.

Every important factual statement should have a source
and page citation.

At the end, provide a Sources section containing the
source and page numbers used.
"""


    # -----------------------------------------------------
    # CALL GEMINI
    # -----------------------------------------------------

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=(
            system_prompt
            + "\n\n"
            + user_prompt
        )
    )


    # -----------------------------------------------------
    # RETURN GENERATED ANSWER
    # -----------------------------------------------------

    return response.text


# ---------------------------------------------------------
# SIMPLE TEST
# ---------------------------------------------------------

if __name__ == "__main__":

    test_evidence = [
        {
            "source": "DIA_Ch01",
            "page": 15,
            "text": (
                "Diabetes can be diagnosed using "
                "A1c, fasting plasma glucose, or "
                "2-hour plasma glucose measurements."
            )
        }
    ]

    answer = generate_answer(
        question="How can diabetes be diagnosed?",
        evidence=test_evidence
    )

    print("\nGenerated Answer:")
    print("=" * 60)
    print(answer)